### ISSUE TITLE
请教一下Supra软件问题

### ISSUE THREAD

**Issue by MichaelFang-eaton** [xjtuecho/AgmPill#1]
大佬您好，

我是一名在校大学生。现在我有个项目已经在Quartus上完成了开发，但想把完成的项目部署到AGM AG576SL144芯片上，想请教您一下如何利用Supra的native模式来开发而不是利用基于Quartus项目转换的Compatible模式来实现。万分感谢！

**Comment by xjtuecho** [comment]
据我了解，目前AGM器件综合还是要利用Quartus来完成，布局布线利用Supra，AGM的文档有详细介绍，按照文档操作即可。
