### ISSUE TITLE
如何烧写CPLD AG256SL100？- How to flash CPLD AG256SL100?

### ISSUE THREAD

**Issue by jLynx** [xjtuecho/AgmPill#2]
嗨，抱歉我的中文不好，我正在使用翻译器。 我已经成功地按照您的 AG256SL100 教程进行操作，并使用 Supra 获得了输出文件。 然后如何将其闪存到 AG256SL100 上？ 我使用什么文件，它是 .svf 吗？

---

Hi, sorry for my bad Chinese, I am using a translator. I have successfully followed your tutorial for the AG256SL100 and got the output files with Supra. How do I then flash it onto the AG256SL100? What file do I use, is it the .svf?

**Comment by xjtuecho** [comment]
Use Supra to flash .prg to AG256SL100. btw, you need a USB-Blaster programmer.

**Comment by jLynx** [comment]
Thank you, I will test when my usb-blaster arrives

**Comment by jLynx** [comment]
Thank you, that works. Now do you know how I change the reset (DEV_CLRn) pin?
Right now its set to pin 44, but I want to change it to pin 40 
![image](https://github.com/xjtuecho/AgmPill/assets/4393979/2f5f4659-2c99-4903-a2a8-b29cba4554e1)
