### ISSUE TITLE
关于GreenPill 烧写器的问题

### ISSUE THREAD

**Issue by huhu6608** [xjtuecho/AgmPill#3]
您好，GreenPill 电路图中的U3 CH552 是用来模拟jtag的吧，有没有固件提供。谢谢！

**Comment by xjtuecho** [comment]
那个是USB-Blaster，固件在另外一个仓库CH552Nano中，https://github.com/xjtuecho/CH552Nano

**Comment by huhu6608** [comment]
好的 谢谢您！
